config/routes.rb
DrydiaryCom::Application.routes.draw do

  devise_for :users, controllers: { registrations: "registrations" }

  resources :days, only: [:create, :update]

  get ':username' => 'dry#show', as: :profile
  get ':username/:year/:month/:day' => 'days#show'
  get ':username/:year/:month/:day/edit' => 'days#edit'

  root 'dry#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_pagination.html.erb
<%= content_tag :div, class: 'pagination', data: { page: page } do %>
  <%= link_to "Older posts", profile_path(user.username, page: page + 1), class: 'next' %>
  <%= link_to "Newer posts", profile_path(user.username, page: page - 1), class: "prev #{'hidden' if page == 1}" %>
<% end %>

app/views/application/_ribbon.html.erb
<%= content_for :ribbon do %>
  <div class="ribbon">
    <h1 id="ribbon-content">
      <%= user.username %>
      <small>is on <%= user.preferred_pronoun %></small>
      <span class="dry-ordinal"><%= user.tally.ordinalize %></span>
      <small>day without <%= user.addiction %></small>
    </h1>
  </div>
<% end %>

app/views/application/_tick.html.erb
<div class="tick-box">
  <%= form_for day, remote: true, html: { id: dated_dom_id(day, :edit), class: 'tick-form' } do |f| %>
    <%= f.hidden_field :ticked, id: dated_dom_id(day, :ticked), value: day.ticked %>
    <%= f.hidden_field :date, id: dated_dom_id(day, :date) %>
    <%= f.submit '', name: 'tick', class: tick_icon_class(day) %>
  <% end %>
</div>

app/views/application/_tick_read_only.html.erb
<div class="tick-box">
  <div class="<%= tick_icon_class(day) %>"></div>
</div>